@Hospital_OPD___Appointment_Management_System__HAMS__HostAddress = http://localhost:5253

GET {{Hospital_OPD___Appointment_Management_System__HAMS__HostAddress}}/weatherforecast/
Accept: application/json

###
